name: "$(date:yyyy-MM-dd)_$(rev:rr)"

trigger: none

pr:
  - main

pool:
  vmImage: "windows-latest"

steps:
  # System.PullRequest.TargetBranch is always 'refs/heads/BRANCH_NAME'
  # so removing first 11 characters ('refs/heads/') gives us the branch name
  - pwsh: echo "##vso[task.setvariable variable=nxbase]origin/$('$(System.PullRequest.TargetBranch)'.substring(11))"
    displayName: "Set --base for nx"

  - pwsh: echo "##vso[task.setvariable variable=nxhead]origin/$('$(System.PullRequest.SourceBranch)'.substring(11))"
    displayName: "Set --head for nx"

  - template: templates/setup-and-build.yml
    parameters:
      nxbase: $(nxbase)
      nxhead: $(nxhead)
